---
env:
  - distribution: centos
    version: 6
  - distribution: centos
    version: 7

services:
  - docker

before_install:
  - docker pull ${distribution}:${version}
  - docker build --no-cache --rm --file=.travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible .travis

script:
  - container_id=$(mktemp)
  
  - docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/nginx-more:ro ${distribution}-${version}:ansible > "${container_id}"
  - docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/nginx-more/.travis/test.yml --syntax-check
  - docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/nginx-more/.travis/test.yml
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/nginx-more/.travis/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - docker exec "$(cat ${container_id})" nginx -V
  - >
    sudo docker exec "$(cat ${container_id})" bash -c "echo 'Nginx-more on Docker ${distribution}:${version}' > /usr/share/nginx/html/index.html && curl -s 127.0.0.1" 
    | grep -q "Nginx-more on Docker ${distribution}:${version}"
    && (echo 'Nginx started: pass' && exit 0)
    || (echo 'Nginx started: fail' && exit 1)
  - docker rm -f "$(cat ${container_id})"